resources:
  limits:
    memory: 512Mi
    cpu: 1500m
  
  requests:
    memory: 512Mi
    cpu: 1500m

minecraftServer:
    # This must be overridden, since we can't accept this for the user.
    eula: "TRUE"
    ops: Khujon
    version: "1.15.2"

livenessProbe:
    command:
        - mcstatus
        - localhost:25565
        - status
    initialDelaySeconds: 180
    periodSeconds: 10
    
readinessProbe:
    command:
        - mcstatus
        - localhost:25565
        - status
    initialDelaySeconds: 180
    periodSeconds: 10